spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password_admin
  data:
    redis:
      host: localhost
      port: 6379
      username: machine_user
      password: machine_user_password
      database: 0
logging:
  level:
    org.springframework.integration.mqtt: DEBUG